odevpl/wdp-2103-01

- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
- src/components/common/ProductBox/ProductBox.test.js
- src/redux/initialState.js
Dodanie możliwości wyświetlania starej ceny na karcie produktu.
> WDP210301-6

- src/components/common/FeatureBox/FeatureBox.module.scss
- src/components/features/FeatureBoxes/FeatureBoxes.js
> Chodzi o elementy "Free shipping", etc.
> Pierwszy element ma ustawiony na sztywno stan "hover". Każda z korzyści powinna być linkiem i mieć hover.
Linki i hovery zrobione.
> WDP210301-3

- src/components/features/ProductSearch/ProductSearch.module.scss
> Select nie jest prawidłowo ostylowany:
> - chyba zły rozmiar czcionki
> - zostaje outline po zmianie kategorii
> - brak hoverów
> 
> Do poprawy wedle designu.
W sumie _do poprawy wedle designu_ a chyba nie mamy nigdzie designu hovera selectu, nie? Chyba że jestem ślepy ;p Zrobiłem wobec powyższego tak jak mi się wydawało że będzie ok : )
> WDP210301-7

- src/components/common/Swipeable/Swipeable.js
- src/components/common/Swipeable/Swipeable.test.js
- src/components/features/NewFurniture/NewFurniture.js
Stworzenie komponentu Swipeable, który może wrappować inne komponenty umożliwiając obsługę akcji swipe.
Użycie tego komponentu w NewFurnitures (usunęłam przy okazji kilka błędów, które logowały mi się w konsoli).
Poza eventami dotykowymi jest możliwość włączenia reakcji na proste eventy myszy, żeby wytestować Swipeable.
Stworzenie prostych testów symulujących event dotykowy i myszy.
> WDP210301-13

- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
- src/components/features/NewFurniture/NewFurniture.js
Dodane klasy favorite i compare do ProductBox.
Również dodany props number, którego wartość jest przypisywana podczas mapowania. Zrobiłem to, aby mieć dostęp do poszczególnyych ProductBoxów, których Buttonom nadałem odpowiednie klasy - zgodnie z treścią taska - czyli jeden z z wciśniętym przyciskiem favorite, drugi z compare i trzeci z oboma.
> Add classes favorite and compare to PRoductBox

- src/components/features/NewFurniture/NewFurniture.js
- src/components/layout/CompanyClaim/CompanyClaim.js
- src/components/layout/CompanyClaim/CompanyClaim.module.scss
- src/components/layout/TopBar/TopBar.js
- src/components/layout/TopBar/TopBar.module.scss
Poprawiony widok elementów na małych rozdzielczościach dla TopBara i Bannera. + fix buga związanego z moim błędem **(wyjaśnienie na czacie)
> Wdp210301 15

- src/components/features/ProductSearch/ProductSearch.js
- src/components/features/ProductSearch/ProductSearch.module.scss
- src/components/layout/MenuBar/MenuBar.js
- src/components/layout/MenuBar/MenuBar.module.scss
Wymiana selecta na sturkturę div>ul>li w komponencie ProductSearch i ostylowanie rozwijania wyboru na hover.
> WDP210301-10

- src/components/features/Promoted/Promoted.js
- src/components/features/Promoted/Promoted.module.scss
- src/components/views/Homepage/Homepage.js
- src/redux/initialState.js
Dodałem komponent Promoted, który zawiera sekcję "Promowane". Dużo zabawy z CSS. :D
> Add component Promoted

- src/components/common/Button/Button.js
- src/components/common/Button/Button.module.scss
- src/components/common/Button/Button.test.js
- src/components/features/Promoted/Promoted.js
- src/components/features/Promoted/Promoted.module.scss
Podpięłam style do defaultowej klasy main komponentu Button. Próbowałam testować, ale doszłam do tego, że nie umiem sprawdzić wygenerowanych z cssa styli. Naprawiłam Button w komponencie Promoted, który się wysypał po moich poprawkach.
> WDP210301-61

- src/App.js
- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBox.module.scss
- src/components/common/ProductBox/ProductBoxContainer.js
- src/components/features/Cart/Cart.js
- src/components/features/Cart/Cart.module.scss
- src/components/features/Cart/Cart.test.js
- src/components/features/Cart/CartContainer.js
- src/components/features/NewFurniture/NewFurniture.module.scss
- src/components/layout/CompanyClaim/CompanyClaim.js
- src/components/layout/CompanyClaim/CompanyClaim.module.scss
- src/components/views/Products/Products.js
- src/components/views/Products/Products.module.scss
- src/styles/settings.scss
Wydzieliłam komponent koszyka. Napisałam jego container, żeby wyświetlał ilość produktów. Dodawanie do koszyka jest w tej chwili zrobione z ProductBox, bo tylko w tym miejscu była gotowa funkcjonalność. Promowane i Galeria też będą  musiały mieć zrobione dodawanie do koszyka. Produkt w koszyku ma mniej właściwości niż ten w głównym storze. Wybrałam te, które moim zdaniem mogą być potrzebne do wyświetlania w koszyku i procesowania zamówienia.
> WDP210301-42 Adding to cart

- src/components/features/Deals/Deals.js
- src/components/features/Deals/Deals.test.js
- src/components/features/NewFurniture/NewFurniture.js
- src/redux/initialState.js
> Zadaniem jest stworzenie wersji mobilnych sekcji "Promocje". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
> Na szerokościach, gdzie trzy boxy nie mieszczą się obok siebie, należy ułożyć je jeden pod drugim (największy na górze, pod nim dwa mniejsze).
RWD dla Deals dodane.
> WDP210301-26

- src/components/common/ProductBox/ProductBox.js
- src/components/common/ProductBox/ProductBoxContainer.js
- src/components/features/NewFurniture/NewFurniture.js
- src/redux/favoritesRedux.js
- src/redux/favouritesRedux.js
- src/redux/initialState.js
- src/redux/localStorage.js
- src/redux/store.js
Zapisywanie ulubionych w LocalStorage. Wydzieliłam w storze favouritesRedux, żeby łatwiej mi było zapisywać i wczytywać tylko tą tablicę. Przy okazji zrefaktorowałam kontener ProductBoxa, bo dostawał 3 razy te same propsy (2 razy z góry i jeszcze ze stora).
> WDP210301-37 Favorites in LocalStorage

- src/App.js
- src/components/layout/Footer/Footer.js
- src/components/views/Account/Account.js
- src/components/views/Account/Account.module.scss
- src/components/views/Account/Account.test.js
- src/components/views/Info/Info.js
- src/components/views/Info/Info.module.scss
- src/components/views/Info/Info.test.js
- src/components/views/Orders/Orders.js
- src/components/views/Orders/Orders.module.scss
- src/components/views/Orders/Orders.test.js
Linki w Footer prowadzą do 3 nowych komponentów widoków. Widoki renderują tylko tytuł, który jest generowany na podstawie urla.
> WDP210301-54 footer links

- src/App.js
- src/components/features/Brands/Brands.js
> Zadaniem jest stworzenie wersji mobilnych sekcji "Brands". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
> W sliderze ma być tyle elementów, ile zmieści się w całości na danej szerokości ekranu.
> Ma działać przesuwanie slajdów za pomocą komponentu Swipeable (jest na niego osobne zadanie – jeśli nie jest gotowe to trzeba przygotować funkcje, które będą wykonywane przy swipe w lewo i w prawo).
RWD i funkcje do swipe zrobione.
> WDP210301-32

- src/components/features/SizeFilter/SizeFilter.js
- src/components/features/SizeFilter/SizeFilter.module.scss
- src/components/views/ProductList/ProductList.js
- src/styles/global.scss
- src/styles/settings.scss
> Twoim zadaniem jest stworzenie filtra rozmiarów zgodnie z wizualizacją dołączoną do ticketu.
> Ticket nie dotyczy funkcjonalności ani RWD.
Filtr rozmiarów gotowy :)
> WDP210301-48

- src/components/features/TagFilter/TagFilter.js
- src/components/features/TagFilter/TagFilter.module.scss
- src/components/features/TagFilter/TagFilterContainer.js
- src/components/views/ProductList/ProductList.js
- src/redux/initialState.js
- src/redux/tagsRedux.js
- src/styles/settings.scss
> Twoim zadaniem jest stworzenie filtra tagów zgodnie z wizualizacją dołączoną do ticketu.
> Ticket nie dotyczy funkcjonalności ani RWD.
Filtr tagów zrobiony, usunąłem też zdublowaną tablicę `Brands` z `initialState`, bo na początku pliku była jej pierwotna wersja, a na końcu pełna.
> WDP210301-50

- src/components/features/NewFurniture/NewFurniture.js
> Po ostatnich zmianach kodu sekcja new furniture rozciąga się na całą szerokość strony. Twoim zadaniem jest wyrównanie do szerokości kontenera strony.
Bug naprawiony (nie wiem który to już raz ;p ).
> WDP210301-67

- src/components/common/ProductBox/ProductBoxContainer.js
- src/components/views/ProductList/ProductList.test.js
Zrobiłam potrzebny import funkcji toggleStar i wydaje mi się, że jest ok. Naprawiłam test ProductList bo husky mi nie puszczał bez tego commitu.
> WDP210301-69 star bug

- src/language.js
Tłumaczenie dotyczy głównie widoku Home. Plik trzeba będzie uzupełniać o nowo powstające komponenty oraz widoki.
> Add language.js

- src/components/features/CategoryFilter/CategoryFilter.module.scss
- src/components/features/Gallery/Gallery.js
- src/components/features/Gallery/Gallery.module.scss
Poza RWD dla Gallery, dodałam też drobne zmiany dla CategoryFilter.module.scss, których nie zdążyłam nanieść w odpowiednim zadaniu - wcześniej usunięte marginesy były niezbędne dla widoczności filtru, ale po restrukturyzacji ProductList i przeniesieniu filtrów do div-3 zaczęły przeszkadzać, zamiast pomagać. :)
> WDP210301-29

- src/components/features/ProductPopup/ProductPopup.js
- src/components/views/Register/Register.js
- src/components/views/Register/Register.module.scss
- src/styles/settings.scss
Walidacja formularza dodana. Pod każdym inputem, w przypadku niespełnienia warunków podświetla się informacja. 
Jedyne czego nie udało mi się zrobić, to aby na bieżąco była sprawdzane, czy jedno hasło jest równe drugiemu - to jest sprawdzane dopiero w momencie kliknięcia przycisku 'Register'. 
Ponieważ idą Święta i jutro ani pojutrze na pewno do tego nie usiądę, bardzo proszę o wyrozumiałość i przymknięcie oka na tę małą niedoróbkę 💯 
Przy okazji całkowicie zmieniłem wygląd, żeby pasował do ekranu logowania zrobionego przez Szymona.
Poprawiłem też propTypes Popupa 👍
> Walidacja formularza rejestracji.

- src/components/features/FeatureBoxes/FeatureBoxes.module.scss
- src/components/features/Promoted/Promoted.js
- src/components/features/Promoted/Promoted.module.scss
> Zadaniem jest stworzenie wersji mobilnych sekcji "Promowane". Klient nie ma designów RWD, więc trzeba zrobić na własną rękę. 
> Na szerokościach mobile należy ukryć lewy slider ("Hot deals") i pokazywać tylko prawy, na całą szerokość containera.
> Ma działać przesuwanie slajdów za pomocą komponentu Swipeable (jest na niego osobne zadanie – jeśli nie jest gotowe to trzeba przygotować funkcje, które będą wykonywane przy swipe w lewo i w prawo).
RWD dodane. Jeśli chodzi o `Swipeable` to oczywiście Dorota była szybsza niż to zadanie, i stworzyła komponent `Slider`, który zawiera w sobie `Swipeable` i pięknie już działa w `Promoted` :D
> WDP210301-24

- src/components/features/PriceFilter/PriceFilter.js
- src/components/features/PriceFilter/PriceFilter.module.scss
- src/components/features/PriceFilter/PriceFilterContainer.js
- src/components/views/ProductList/ProductList.js
- src/components/views/ProductList/ProductListContainer.js
- src/redux/initialState.js
- src/redux/priceRedux.js
- src/redux/productsRedux.js
- src/redux/store.js
- src/styles/settings.scss
> Twoim zadaniem jest filtrowanie produktów na podstronie shop.
> Zawężenie pola ma pokazać tylko te produkty, które mieszczą się pomiędzy przedziałem cenowym wyznaczonym przez filter.
> Należy też skasować przycisk filter. Filtrowanie ma być wyzwalane poprzez przesuwanie znaczników.
Wydaje mi się, że działa :)
> WDP210301-57

- src/components/features/Gallery/Gallery.js
- src/components/features/Gallery/Gallery.module.scss
Product w galeri przestał rozciągać się na całą wysokość kolumny. Naprawione.
> Fix flexible display of gallery product

- src/components/features/ProductBox/GridProduct/GridProduct.js
- src/components/features/ProductBox/ProductBox.js
- src/components/views/ProductList/ProductList.test.js
Błąd przy próbie wywołanie quick view z listy produktów i galerii.
Zrobiłam:
- usunęłam dodatkowy kod, który pojawił się w ProductBox w czasie wcześniejszego merga
- dodałam warunek sprawdzający czy funkcje onModalOpen i close zostały przekazane do ProductBox - to eliminuje bug
- zmieniłam test ProductList, żeby mi puściło commit
> Fix quick view modal
